import Vue from 'vue';
import { Button } from 'vant';
import { Tabbar, TabbarItem } from 'vant';
import { Icon } from 'vant';
import { Search } from 'vant';
import { NavBar } from 'vant';
import { Toast } from 'vant';
import { List } from 'vant';
import { Swipe, SwipeItem } from 'vant';
import { Sidebar, SidebarItem } from 'vant';
import { Divider } from 'vant';
import { Tab, Tabs } from 'vant';
import { Sku } from 'vant';
import { GoodsAction, GoodsActionIcon, GoodsActionButton } from 'vant';
import { Popup } from 'vant';
import { Cell, CellGroup } from 'vant';
import { Stepper } from 'vant';
import { Form } from 'vant';
import { Grid, GridItem } from 'vant';
import { SwipeCell } from 'vant';
import { Card } from 'vant';
import { Checkbox, CheckboxGroup } from 'vant';
import { ContactCard } from 'vant';
import { Col, Row } from 'vant';
import { Sticky } from 'vant';
import { AddressList } from 'vant';
import { AddressEdit } from 'vant';
import { Area } from 'vant';

Vue.use(Area);
Vue.use(AddressEdit);
Vue.use(AddressList);
Vue.use(Sticky);
Vue.use(Col);
Vue.use(Row)
Vue.use(ContactCard);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Card);
Vue.use(SwipeCell);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Form);
Vue.use(Stepper);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Popup);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Sku);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Divider);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(List)
Vue.use(Toast);
Vue.use(NavBar);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Search);
Vue.use(Icon);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Button);